//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItronicStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaPrimke
    {
        public int PrimkaID { get; set; }
        public int ProizvodID { get; set; }
        public int Kolicina { get; set; }
    
        public virtual Primka Primka { get; set; }
        public virtual Proizvod Proizvod { get; set; }
    }
}
