//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItronicClassLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int IDPovratnaInformacija { get; set; }
        public int IDKorisnik { get; set; }
        public int IDReklamacija { get; set; }
        public int Status { get; set; }
        public string Odgovor { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Reklamacija Reklamacija { get; set; }
    }
}
