//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItronicClassLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financije
    {
        public int IDFinancije { get; set; }
        public int IDRacun { get; set; }
        public int IDPrimka { get; set; }
        public Nullable<double> Prihodi { get; set; }
        public Nullable<double> Rashodi { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        public virtual Primka Primka { get; set; }
        public virtual Racun Racun { get; set; }
    }
}
