//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obracun
    {
        public int ID { get; set; }
        public double Prihod { get; set; }
        public double Rashod { get; set; }
        public int Godina { get; set; }
        public int Mjesec { get; set; }
        public int Prodano { get; set; }
        public int Nabavljeno { get; set; }
    
        public virtual Kvartal Kvartal { get; set; }
    }
}
