//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odgovor
    {
        public int ID { get; set; }
        public int IDAdmin { get; set; }
        public int IDReklamacija { get; set; }
        public System.DateTime Datum { get; set; }
        public string Odgovor1 { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Reklamacija Reklamacija { get; set; }
    }
}
