//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzija
    {
        public int ID { get; set; }
        public int IDKorisnik { get; set; }
        public int IDProizvod { get; set; }
        public int Ocjena { get; set; }
        public System.DateTime Datum { get; set; }
        public string Komentar { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Proizvod Proizvod { get; set; }
    }
}
